version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: social-postgres
    env_file:
      - ./.environment/docker/.env.postgres
    ports:
      - '5434:5432'           
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - microservice-net

  minio:
    image: minio/minio
    container_name: social-minio
    command: server /data --console-address ":9001"
    ports:
      - '9000:9000'           
      - '9001:9001'          
    env_file:
      - ./.environment/docker/.env.minio
    volumes:
      - minio_data:/data
    networks:
      - microservice-net

  rabbitmq:
    image: rabbitmq:3-management
    container_name: social-rabbitmq
    ports:
      - '5672:5672'           
      - '15672:15672'         
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    networks:
      - microservice-net
    restart: always


volumes:
  pgdata:
  minio_data:

networks:
  microservice-net:
    external: true